<?php

namespace Database\Seeders;

use App\Models\Workout;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WorkoutsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $workouts = [
            "High-Intensity Interval Training (HIIT)",
            "CrossFit Circuit Blast",
            "Cardio Kickboxing",
            "Powerlifting Party",
            "Yoga Fusion Flow",
            "Bootcamp Bonanza",
            "Core Crusher Challenge",
            "Tabata Torch",
            "Spin Sprint Session",
            "Functional Fitness Fiesta",
            "Pilates Power Hour",
            "MMA Madness",
            "Agility Agility Attack",
            "TRX Total Body Takedown",
            "Zumba Dance Delight",
            "Barre Burnout",
            "Kettlebell Khaos",
            "Circuit City",
            "Aerial Acrobatics Adventure",
            "Rowing Rampage",
            "Bodyweight Bliss",
            "Step Aerobics Extravaganza",
            "Mindful Meditation Marathon",
            "Plyometric Party",
            "Synchronized Swimming Sweat Session",
            "Dancehall Dynamic Duo",
            "Hiking Hurdles",
            "Sprint and Stretch",
            "Karate Kata Cardio",
            "Ropes and Reps",
            "Aqua Aerobics Affair",
            "BodyCombat Battle",
            "Rock Climbing Rendezvous",
            "Parkour Power-Up",
            "Tai Chi Tranquility",
            "Mountain Biking Mayhem",
            "Wrestling Workout War",
            "Balance Ball Blast",
            "Battle Ropes Bonfire",
            "Boxing Blitz",
            "Inversion Immersion",
            "Stairway to Fitness",
            "Medicine Ball Mayhem",
            "Jump Rope Jamboree",
            "Surfset Strength",
            "Skating Skills Showdown",
            "Hula Hoop Hysteria"
        ];

        $descriptions = [
            "A high-energy workout involving short bursts of intense exercise.",
            "A challenging CrossFit circuit to boost strength and endurance.",
            "A cardiovascular workout with elements of kickboxing techniques.",
            "A weightlifting party focusing on powerlifting movements.",
            "A yoga session that combines different yoga styles for a flowy experience.",
            "A dynamic and intense bootcamp-style workout.",
            "An intense core-focused workout designed to challenge your midsection.",
            "A workout based on the Tabata protocol, a form of high-intensity interval training.",
            "An energetic spinning session for cardiovascular fitness.",
            "A functional fitness workout targeting various muscle groups.",
            "A Pilates session emphasizing core strength and flexibility.",
            "Mixed Martial Arts-inspired workout for a full-body challenge.",
            "An agility-focused workout to enhance coordination and speed.",
            "Total Body Resistance Exercise using TRX straps for a comprehensive workout.",
            "A dance-inspired workout with Latin rhythms for a fun cardio session.",
            "Ballet-inspired workout to strengthen and tone muscles.",
            "A kettlebell workout to improve strength, power, and endurance.",
            "A circuit-style workout incorporating various exercises.",
            "Aerial silks and hoop exercises for a unique full-body workout.",
            "Rowing machine workout to build strength and cardiovascular fitness.",
            "A bodyweight-only workout for strength and flexibility.",
            "Step aerobics routine for cardiovascular fitness and leg strength.",
            "Mindful meditation combined with light exercises for overall well-being.",
            "Explosive movements for power and strength development.",
            "Combining swimming drills with full-body exercises for a unique workout.",
            "Dancehall dance moves paired with dynamic exercises.",
            "A hike with added exercises for a full-body outdoor workout.",
            "Short sprints followed by stretching for a quick yet effective session.",
            "Karate-inspired movements for a cardio and strength workout.",
            "Battle ropes exercises for a challenging upper body and cardio workout.",
            "Aquatic workout for low-impact resistance training.",
            "Mixed martial arts-inspired workout for cardio and strength.",
            "Rock climbing drills for upper body and grip strength.",
            "Parkour movements for agility and full-body conditioning.",
            "Tai Chi movements for balance, flexibility, and relaxation.",
            "Mountain biking with intermittent strength and cardio intervals.",
            "Wrestling-inspired drills for a full-body workout.",
            "Balance ball exercises for core stability and strength.",
            "Intense battle ropes workout for upper body and cardiovascular endurance.",
            "Boxing drills for cardio, agility, and strength.",
            "Inversion exercises for core strength and balance.",
            "Stair climbing with added exercises for a full-body challenge.",
            "Medicine ball exercises for strength, power, and coordination.",
            "Jump rope exercises for cardiovascular fitness and coordination.",
            "Surfing-inspired balance and strength workout.",
            "Skating drills for lower body strength and endurance.",
            "Hula hoop exercises for core strength and coordination."
        ];
        

        $instructions = [
            "Follow the instructor's cues for intervals of high-intensity exercises.",
            "Complete each exercise in the circuit for the specified duration.",
            "Combine cardio and kickboxing moves in this energetic session.",
            "Lift heavy weights with proper form for maximum powerlifting benefits.",
            "Flow through yoga poses, focusing on breath and movement.",
            "Engage in a variety of exercises in a bootcamp format.",
            "Perform core exercises with proper form and controlled movements.",
            "Alternate between 20 seconds of intense exercise and 10 seconds of rest.",
            "Adjust resistance and speed on the spin bike for an effective session.",
            "Use functional movements to enhance overall fitness.",
            "Focus on controlled movements and core engagement in Pilates exercises.",
            "Embrace the intensity of mixed martial arts moves for a full-body workout.",
            "Improve agility with quick, dynamic movements and coordination exercises.",
            "Utilize TRX straps for a challenging total body workout.",
            "Dance to the rhythm and enjoy a cardio workout with Zumba.",
            "Channel your inner ballerina for a workout that targets strength and grace.",
            "Swing kettlebells with proper form to enhance strength and endurance.",
            "Complete a series of exercises in a circuit for a well-rounded workout.",
            "Perform aerial exercises for a unique and engaging full-body workout.",
            "Row with proper technique to build strength and cardiovascular endurance.",
            "Use your body weight for a workout that can be done anywhere.",
            "Step up and down with precision for a cardio and leg workout.",
            "Combine mindfulness and light exercise for a holistic well-being session.",
            "Engage in explosive movements to enhance power and strength.",
            "Incorporate swimming drills with bodyweight exercises for a challenge.",
            "Dance to the upbeat rhythm of Dancehall music while working out.",
            "Hike while incorporating strength and cardio exercises for added challenge.",
            "Sprint for short distances followed by stretching for flexibility.",
            "Execute karate-inspired movements for a cardio and strength boost.",
            "Move battle ropes in various patterns for upper body and cardio benefits.",
            "Perform exercises in the water for a low-impact resistance workout.",
            "Combine martial arts moves for a cardio and strength-building routine.",
            "Climb rocks for upper body strength and challenge your overall fitness.",
            "Navigate through obstacles using parkour techniques for agility.",
            "Practice Tai Chi movements for balance, flexibility, and relaxation.",
            "Mountain bike with intermittent strength and cardio intervals.",
            "Engage in wrestling-inspired exercises for a full-body workout.",
            "Stabilize on a balance ball while performing core exercises.",
            "Move battle ropes in a challenging routine for upper body strength.",
            "Throw punches and kicks for a cardio and agility workout in boxing.",
            "Perform exercises in an inverted position for core strength.",
            "Climb stairs with additional exercises for a full-body challenge.",
            "Utilize a medicine ball for strength, power, and coordination.",
            "Jump rope for cardiovascular fitness and improved coordination.",
            "Simulate surfing movements on a stability board for balance and strength.",
            "Rollerblade or ice skate for lower body strength and endurance.",
            "Swing a hula hoop for core strength and coordination."
        ];

        foreach ($workouts as $key => $workout) {
            Workout::create([
                'name' => $workout,
                'description' => $descriptions[$key],
                'instructions' => $instructions[$key],
                'duration' => rand(10, 120),
            ]);
        }
    }
}
